apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: appsody-manual-pipeline-run
spec:
  serviceAccountName: service-account-dinesh
  timeout: "1h0m0s"  
  pipelineRef:
    name: appsody-build-pipeline
  resources:
    - name: git-sources
      resourceRef:
        name: git-sources
    - name: docker-images
      resourceRef:
        name: docker-images
