apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: appsody-build-pipeline
spec:
  resources:
    - name: git-sources
      type: git
    - name: docker-images
      type: image
  tasks:
    - name: appsody-build
      taskRef:
        name: appsody-build-push-deploy-task
      resources:
        inputs:
        - name: git-sources
          resource: git-sources
        - name: docker-images
          resource: docker-images
      params:
      - name: app-deploy-file-name
        value: app-deploy.yaml
